name: Build DOCX → HTML (Pandoc + MathJax) and Deploy to Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'theme/**'
      - 'scripts/**'
      - 'Dockerfile'
      - '.github/workflows/build-and-deploy.yml'
  workflow_dispatch: {}
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image (builder stage only)
        run: |
          docker build --target builder \
            -t site-builder:latest \
            --build-arg SRC_DOC=src/Kinetics_Appendix.docx \
            --build-arg TITLE="Kinetics Appendix" \
            .
      - name: Extract site/ from image
        run: |
          id=$(docker create site-builder:latest)
          mkdir -p site
          docker cp "$id":/app/site ./site
          docker rm "$id"
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
