name: Publish static site to gh-pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'scripts/**'
      - 'theme/**'
      - 'Dockerfile'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site (Docker builder stage)
        run: |
          docker build --target builder -t site-builder:latest .
          id=$(docker create site-builder:latest)
          rm -rf site
          mkdir -p site
          docker cp "$id":/app/site/. ./site
          docker rm "$id"
          echo "Site tree:"; find site -maxdepth 2 -print
          test -f site/index.html || (echo "Missing site/index.html!" && exit 1)

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          clean: true
